CREATE TABLE Customer(
	Cust_ID		    CHAR(5)       Not Null,
  C_Address		  VARCHAR(50)   Not Null,
  C_City		    VARCHAR(20)   Not Null,
  C_State		    CHAR(2)       Not Null,
  C_ZipCode	    NUMBER(5,0)   Not Null,
  C_Email		    VARCHAR(50)   Not Null,
  PRIMARY KEY (Cust_ID));
  
INSERT INTO Customer VALUES(25987, '12 Knuckle Lane', 'Austin', 'TX', 73301,'jojoad@gmail.com');  
INSERT INTO Customer VALUES(28549, '1 Florence Rd', 'Boston', 'MA', 02108, 'notthatfx@gmail.com'); 
INSERT INTO Customer VALUES(35872, '3 Flapjack Cir.', 'Denver', 'CO', 80123, 'cccsss@gmail.com'); 
INSERT INTO Customer VALUES(16598, '14 13th Street', 'Austin', 'TX', 73301,'pancakes45@gmail.com');  
INSERT INTO Customer VALUES(36879, '11 Greens Lane', 'Boston', 'MA', 02108, '12345667@gmail.com'); 
INSERT INTO Customer VALUES(16489, '6 Flapjack Cir.', 'Denver', 'CO', 80123, 'imataduda@gmail.com');

SELECT* FROM Customer;

ALTER TABLE SALES_RECEIPT ADD PRIMARY KEY (Sale_ID);
ALTER TABLE MOREBOOKS ADD PRIMARY KEY (B_code);

CREATE TABLE Sales_Detail(
	Sale_ID		        NUMBER(5)       Not Null,
  Sale_Nbr		      NUMBER(2)   Not Null,
  B_code		        VARCHAR(4)   Not Null,
  SS_nbr_purchased	NUMBER(3)       Not Null,
  line_total	      NUMBER(7,2),
  CONSTRAINT SaleDetail_PK PRIMARY KEY (Sale_ID, Sale_Nbr),
    FOREIGN KEY (Sale_ID) REFERENCES SALES_RECEIPT,
    FOREIGN KEY (B_code) REFERENCES MOREBOOKS);

INSERT INTO Sales_Detail VALUES(10000, 1, '0180', 1, NULL);  
INSERT INTO Sales_Detail VALUES(10025, 1, '079X', 2, NULL); 
INSERT INTO Sales_Detail VALUES(10040, 1, '7559', 2, NULL); 
INSERT INTO Sales_Detail VALUES(10040, 2, '1351', 1, NULL); 

ALTER TABLE SALES_RECEIPT ADD PRIMARY KEY (Sale_ID);
ALTER TABLE MOREBOOKS ADD PRIMARY KEY (B_code);

ALTER TABLE AUTHORS ADD PRIMARY KEY (ID);
ALTER TABLE BRANCHES ADD PRIMARY KEY (BRANCH);
ALTER TABLE PUBLISHERS ADD PRIMARY KEY (CODE);

ALTER TABLE MOREBOOKS MODIFY (PUBLISHER_CODE  char(2));
ALTER TABLE MOREBOOKS ADD FOREIGN KEY (PUBLISHER_CODE) REFERENCES PUBLISHERS;
ALTER TABLE SALES_RECEIPT MODIFY (Cust_ID CHAR(5));
ALTER TABLE SALES_RECEIPT ADD FOREIGN KEY (Cust_ID) REFERENCES CUSTOMER;
ALTER TABLE SALES_RECEIPT ADD FOREIGN KEY (BR_Code) REFERENCES BRANCHES;
ALTER TABLE BOOKS_BRANCHES ADD CONSTRAINT BookBranches_PK PRIMARY KEY (B_Code, Branch);
ALTER TABLE BOOKS_AUTHORS ADD CONSTRAINT BookAuthors_PK PRIMARY KEY (BOOK_CODE, AUTHOR_ID);
ALTER TABLE BOOKS_BRANCHES ADD FOREIGN KEY (B_Code)REFERENCES MOREBOOKS;
ALTER TABLE BOOKS_BRANCHES ADD FOREIGN KEY (Branch)REFERENCES BRANCHES;
ALTER TABLE BOOKS_AUTHORS ADD FOREIGN KEY (BOOK_CODE)REFERENCES MOREBOOKS;
ALTER TABLE BOOKS_AUTHORS ADD FOREIGN KEY (AUTHOR_ID)REFERENCES AUTHORS;

UPDATE MOREBOOKS 
  SET PRICE = (PRICE*1.1) WHERE PUBLISHER_CODE ='BB';
  
UPDATE BOOKS_BRANCHES 
  SET REORDER_LEVEL = (REORDER_LEVEL+2) WHERE REORDER_LEVEL <=3;
 Commit; 

UPDATE SALES_DETAIL
  SET LINE_TOTAL = (SS_NBR_PURCHASED*8.42)
  WHERE B_CODE='0180';
  
UPDATE SALES_DETAIL
  SET LINE_TOTAL = (SS_NBR_PURCHASED*4.55)
  WHERE B_CODE='079X';
  
UPDATE SALES_DETAIL
  SET LINE_TOTAL = (SS_NBR_PURCHASED*3.95)
  WHERE B_CODE='7559';
  
UPDATE SALES_DETAIL
  SET LINE_TOTAL = (SS_NBR_PURCHASED*6.65)
  WHERE B_CODE='1351';
  
UPDATE SALES_DETAIL
  SET LINE_TOTAL =(SELECT (SALES_DETAIL.SS_NBR_PURCHASED*MOREBOOKS.PRICE) 
  FROM SALES_DETAIL, MOREBOOKS
  WHERE SALES_DETAIL.B_CODE = MOREBOOKS.B_CODE);

/*Books by Author*/
SELECT AUTHORS.LAST_NAME AS "Last Name", AUTHORS.FIRST_NAME AS "First Name",
  MOREBOOKS.TITLE AS "Title", MOREBOOKS.CATEGORY AS "Category", MOREBOOKS.PRICE AS "Price",
  MOREBOOKS.PAPERBACK AS "Paperback", PUBLISHERS.NAME AS "Name", PUBLISHERS.CITY AS "City",
  PUBLISHERS.STATE AS "State"
  FROM AUTHORS, MOREBOOKS, PUBLISHERS, BOOKS_AUTHORS
  WHERE AUTHORS.ID=BOOKS_AUTHORS.AUTHOR_ID 
  AND BOOKS_AUTHORS.BOOK_CODE=MOREBOOKS.B_CODE
  AND MOREBOOKS.PUBLISHER_CODE=PUBLISHERS.CODE
  ORDER BY AUTHORS.LAST_NAME, MOREBOOKS.PRICE;
  
/*Books at Branches*/
SELECT BRANCHES.NAME AS "Name", BRANCHES.LOCATION AS "Location", MOREBOOKS.CATEGORY AS "Category",
  MOREBOOKS.TITLE AS "Title", BOOKS_BRANCHES.ON_HAND AS "On Hand", BOOKS_BRANCHES.REORDER_LEVEL AS "Reorder Level"
  FROM BRANCHES, MOREBOOKS, BOOKS_BRANCHES
  WHERE BRANCHES.BRANCH=BOOKS_BRANCHES.BRANCH
  AND BOOKS_BRANCHES.B_CODE=MOREBOOKS.B_CODE
  ORDER BY BRANCHES.NAME;

  /*Books by Category*/
SELECT MOREBOOKS.CATEGORY AS "Category", MOREBOOKS.TITLE AS "Title", MOREBOOKS.PRICE AS "Price",
  AUTHORS.LAST_NAME AS "Author Last Name"
  FROM AUTHORS, MOREBOOKS, BOOKS_AUTHORS
  WHERE AUTHORS.ID=BOOKS_AUTHORS.AUTHOR_ID 
  AND BOOKS_AUTHORS.BOOK_CODE=MOREBOOKS.B_CODE
  ORDER BY MOREBOOKS.CATEGORY;
  
/*Publishers Books*/
SELECT PUBLISHERS.NAME AS "Name", PUBLISHERS.CITY AS "City", PUBLISHERS.STATE AS "State",
  MOREBOOKS.TITLE AS "Title", MOREBOOKS.PAPERBACK AS "Paperback"
  FROM PUBLISHERS, MOREBOOKS
  WHERE MOREBOOKS.PUBLISHER_CODE=PUBLISHERS.CODE
  ORDER BY PUBLISHERS.CITY DESC, PUBLISHERS.NAME DESC;
  
/*BOOK SALES*/
SELECT AUTHORS.LAST_NAME AS "Last Name", AUTHORS.FIRST_NAME AS "First Name",
  MOREBOOKS.TITLE AS "Title", MOREBOOKS.PRICE AS "Price", SALES_RECEIPT.SALE_DATE AS "Sale Date",
  SALES_DETAIL.SS_NBR_PURCHASED AS "Number Sold"
  FROM AUTHORS, MOREBOOKS, BOOKS_AUTHORS, SALES_RECEIPT, SALES_DETAIL
  WHERE AUTHORS.ID=BOOKS_AUTHORS.AUTHOR_ID 
  AND BOOKS_AUTHORS.BOOK_CODE=MOREBOOKS.B_CODE
  AND MOREBOOKS.B_CODE=SALES_DETAIL.B_CODE
  AND SALES_DETAIL.SALE_ID=SALES_RECEIPT.SALE_ID;
  
 SELECT MOREBOOKS.TITLE AS "Title", AUTHORS.FIRST_NAME||' '||AUTHORS.LAST_NAME AS "Author",
  MOREBOOKS.PRICE AS "Price"
  FROM MOREBOOKS, BOOKS_AUTHORS, AUTHORS
  WHERE AUTHORS.ID=BOOKS_AUTHORS.AUTHOR_ID 
  AND BOOKS_AUTHORS.BOOK_CODE=MOREBOOKS.B_CODE
  AND MOREBOOKS.CATEGORY='MYS';
  
 SELECT CATEGORY, COUNT(CATEGORY) AS "Count"
  FROM MOREBOOKS
  WHERE CATEGORY='MYS'
  GROUP BY CATEGORY;
  
SELECT CATEGORY, COUNT(CATEGORY) AS "Count"
  FROM MOREBOOKS
  GROUP BY CATEGORY;
  
  CREATE VIEW QUESTION11 AS 
SELECT CUSTOMER.C_NAME AS "Customer Name", SALES_RECEIPT.SALE_DATE AS "Sale Date",
  MOREBOOKS.TITLE AS "Title", SALES_DETAIL.SS_NBR_PURCHASED AS "Number Purchased",
  SALES_DETAIL.LINE_TOTAL AS "Total"
  FROM CUSTOMER, SALES_RECEIPT, MOREBOOKS, SALES_DETAIL
  WHERE CUSTOMER.CUST_ID=SALES_RECEIPT.CUST_ID
  AND SALES_RECEIPT.SALE_ID=SALES_DETAIL.SALE_ID
  AND SALES_DETAIL.B_CODE=MOREBOOKS.B_CODE;
  
SELECT "Customer Name", SUM("Number Purchased") AS "Number Purchased", 
SUM("Total" )AS "Sale Total"
  FROM QUESTION11
  WHERE  "Customer Name"='Mick'
  GROUP BY  "Customer Name";
  
SELECT AVG("Total") AS "Average Sale",
  MIN ("Total") AS "Mininum Sale",
  MAX ("Total") AS "Maximum Sale"
  FROM QUESTION11;
  
CREATE VIEW QUESTION15 AS
  SELECT BRANCHES.NAME AS "Branch Name", MOREBOOKS.TITLE AS "Title",
  MOREBOOKS.PRICE AS "Price", BOOKS_BRANCHES.ON_HAND AS "Amount on hand"
  FROM BRANCHES, MOREBOOKS, BOOKS_BRANCHES
  WHERE BRANCHES.BRANCH=BOOKS_BRANCHES.BRANCH
  AND BOOKS_BRANCHES.B_CODE=MOREBOOKS.B_CODE
  ORDER BY BRANCHES.NAME;
  
CREATE VIEW QUESTION16 AS
SELECT SUM(BOOKS_BRANCHES.ON_HAND) AS ONE, 
SUM(BOOKS_BRANCHES.REORDER_LEVEL) AS TWO, 
AVG(MOREBOOKS.PRICE) AS THREE
  FROM BOOKS_BRANCHES, MOREBOOKS
  WHERE BOOKS_BRANCHES.B_CODE=MOREBOOKS.B_CODE;
  
SELECT (ONE+TWO)*THREE
  FROM QUESTION16;
  
 SELECT "Branch Name", SUM("Amount on hand") AS "TOTAL INVENTORY", 
  AVG("Amount on hand") AS "AVERAGE INVENTORY"
  FROM QUESTION15
  GROUP BY "Branch Name"
  ORDER BY "Branch Name" DESC;