DROP TABLE CAR;
DROP TABLE SALESREP;
DROP TABLE CUSTOMER;
DROP TABLE INVOICE;
CREATE TABLE CAR(
	CAR_NUM		  CHAR(2)   Not Null,
	CAR_NAME	  VARCHAR2(30) Not Null,
	CAR_MODEL	  CHAR(6) Not Null,
	CAR_YEAR      NUMBER(4,0) Not Null,
	CAR_PRICE     NUMBER(8,2) Not Null,
	PRIMARY KEY (CAR_NUM));
CREATE TABLE SALESREP (
	S_ID		    CHAR(2)   Not Null,
	S_NAME			VARCHAR2(35) Not Null,
	S_ADDRESS		VARCHAR2(35),
	S_COMM      	NUMBER(2,2),
	PRIMARY KEY (S_ID));
CREATE TABLE CUSTOMER (
	CUS_ID		    CHAR(2)   Not Null,
	CAR_NAME		VARCHAR2(35) Not Null,
	CAR_MODEL		VARCHAR2(35) Not Null,
	PRIMARY KEY (CUS_ID));
CREATE TABLE INVOICE (
	INV_NUM		    CHAR(2)   Not Null,
	INV_DATE		DATE   Not Null,
	S_ID		    CHAR(2)   Not Null,
	CUS_ID		    CHAR(2)   Not Null,
	CAR_NUM       	CHAR(2)   Not Null,
	INV_TOTAL     	NUMBER(9,2),
	PRIMARY KEY (INV_NUM),
	FOREIGN KEY (S_ID) REFERENCES SALESREP,
	FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER,
	FOREIGN KEY (CAR_NUM) REFERENCES CAR);
DESC CAR;
DESC SALESREP;
DESC CUSTOMER;
DESC INVOICE;
COMMIT CAR, SALESREP, CUSTOMER, INVOICE 