/*1*/ALTER TABLE SALESREP
  MODIFY (S_ID  CHAR(15));
ALTER TABLE INVOICE
  MODIFY (S_ID  CHAR(15));
/*2*/ALTER TABLE INVOICE
  MODIFY (INV_NUM  CHAR(5));
/*3*/ALTER TABLE CUSTOMER
  ADD (F_NAME  VARCHAR(35))
  ADD (L_NAME  VARCHAR(35));
/*4*/UPDATE CUSTOMER
  SET F_NAME='Frank', L_NAME='West' WHERE CUS_ID=12;
/*5*/ALTER TABLE CUSTOMER
  DROP COLUMN CUS_NAME;
/*6*/ALTER TABLE CAR
  ADD FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER;
/*7   ROLLBACK; DID NOT DELETE CODE RUN SINCE LAST COMMIT, BUT WORKS WITH 
 SECOND USE OF JUNK LAYOUT CHANGE. */