/*1*/ SELECT INV_DATE, CUS_ID, INV_TOTAL
  FROM INVOICE
  WHERE INV_TOTAL >= 451529;
 /*2*/SELECT INV_DATE, CUS_ID, S_ID, INV_TOTAL
  FROM INVOICE
  WHERE INV_DATE <= '10-21-02';
 /*3*/SELECT CAR_NAME, CAR_MODEL, CAR_PRICE
  FROM CAR
  WHERE CAR_PRICE BETWEEN 500000 AND 650000;
/*4*/SELECT CAR_NAME, CAR_MODEL, CAR_PRICE
  FROM CAR
  WHERE CAR_PRICE IN( 520026.98, 620026.98, 3.98);
/*5*/ALTER SESSION SET NLS_DATE_FORMAT='MM/DD/YYYY';
SELECT INV_DATE, CUS_ID, S_ID, INV_TOTAL
  FROM INVOICE
  WHERE INV_DATE <= '10-21-02' AND INV_TOTAL > 1000;
/*6*/SELECT INV_DATE, CUS_ID, S_ID, INV_TOTAL
  FROM INVOICE
  WHERE INV_DATE <= '10-21-02' OR INV_TOTAL > 1000;
/*7*/SELECT CAR_NAME, CAR_MODEL, CAR_PRICE
  FROM CAR
  WHERE CAR_PRICE NOT BETWEEN 500000 AND 650000;
 /*8*/SELECT *
  FROM CAR
  WHERE CAR_MODEL LIKE '_4%';
SELECT *
  FROM CAR
  WHERE CAR_YEAR LIKE '199_';
 /*9*/SELECT INV_DATE, CUS_ID, S_ID, INV_TOTAL
  FROM INVOICE
  WHERE (INV_DATE <= '10-21-02' OR INV_TOTAL > 1000) OR CAR_NUM = 16;
SELECT INV_DATE, CUS_ID, S_ID, INV_TOTAL
  FROM INVOICE
  WHERE INV_DATE <= '10-21-02' OR (INV_TOTAL > 1000 OR CAR_NUM = 16);
 /*10*/SELECT *
  FROM CUSTOMER
  ORDER BY CUS_NAME ASC;
SELECT *
  FROM CUSTOMER
  ORDER BY CUS_NAME DESC;
 /*11*/SELECT INV_NUM, INV_DATE, CUS_ID, S_ID
  FROM INVOICE
  ORDER BY CUS_ID DESC, INV_NUM ASC;
 /*12*/SELECT INV_NUM AS INVOICE_NUMBER, INV_DATE, CUS_ID AS Customer, S_ID
  FROM INVOICE
  ORDER BY Customer DESC, INVOICE_NUMBER  ASC;