/*1*/SELECT COUNT (DISTINCT CUS_ID)
  FROM INVOICE;
/*2*/SELECT COUNT (DISTINCT CAR_PRICE)
  FROM CAR
  WHERE CAR_PRICE < 500000;
 /*3*/SELECT AVG (CAR_PRICE)
  FROM CAR;
 /*4*/SELECT CAR_PRICE
FROM CAR
WHERE CAR_PRICE > (SELECT AVG (CAR_PRICE) FROM CAR);
SELECT CAR_PRICE
FROM CAR
WHERE CAR_PRICE < (SELECT AVG (CAR_PRICE) FROM CAR);
/*5*/ALTER SESSION SET NLS_DATE_FORMAT='MM/DD/YYYY';
INSERT INTO INVOICE VALUES(6, '11-18-02', 9, 14, 12, NULL);
INSERT INTO INVOICE VALUES(7, '11-18-02', 9, 14, 15, NULL);
/*6*/SELECT SUM (INV_TOTAL)
FROM INVOICE;
SELECT S_ID, SUM (INV_TOTAL)
FROM INVOICE
GROUP BY S_ID;
/*7*/SELECT CUS_ID, AVG (INV_TOTAL)
FROM INVOICE
GROUP BY CUS_ID;
/*8*/CREATE VIEW INVOICE_9 AS
  SELECT INV_NUM, INV_DATE, INV_TOTAL
  FROM INVOICE
  WHERE S_ID=9;
 /*9*/SELECT INVOICE.INV_NUM, INVOICE.CAR_NUM, INVOICE.INV_TOTAL, CUSTOMER.CUS_NAME
	FROM INVOICE, CUSTOMER
	WHERE INVOICE.CUS_ID=CUSTOMER.CUS_ID
	ORDER BY INVOICE.CUS_ID;
SELECT INVOICE.INV_NUM, INVOICE.CAR_NUM, INVOICE.INV_TOTAL, CUSTOMER.CUS_NAME
  FROM INVOICE, CUSTOMER
  WHERE INVOICE.CUS_ID=CUSTOMER.CUS_ID 
  AND INVOICE.INV_NUM > (SELECT AVG (INV_NUM)FROM INVOICE)
  ORDER BY INVOICE.CUS_ID;
 /*10*/CREATE VIEW AVG_INVOICE AS
  SELECT INVOICE.INV_NUM, INVOICE.CAR_NUM, INVOICE.INV_TOTAL, CUSTOMER.CUS_NAME
  FROM INVOICE, CUSTOMER
  WHERE INVOICE.CUS_ID=CUSTOMER.CUS_ID 
  AND INVOICE.INV_NUM > (SELECT AVG (INV_NUM)FROM INVOICE)
  ORDER BY INVOICE.CUS_ID;
  /*11*/SELECT AVG_INVOICE.INV_NUM, AVG_INVOICE.CAR_NUM, AVG_INVOICE.INV_TOTAL, 
  AVG_INVOICE.CUS_NAME, CAR.CAR_NAME, CAR.CAR_MODEL
  FROM AVG_INVOICE, CAR
  WHERE AVG_INVOICE.CAR_NUM = CAR.CAR_NUM ;
  /*12*/SELECT SALESREP.S_NAME, INVOICE.INV_NUM, INVOICE.INV_TOTAL, 
  (INVOICE.INV_TOTAL*SALESREP.S_COMM) AS "Total Commission",
  ((INVOICE.INV_TOTAL*SALESREP.S_COMM)+INVOICE.INV_TOTAL) AS "Total Sale"
  FROM SALESREP, INVOICE
  WHERE INVOICE.S_ID = SALESREP.S_ID
  ORDER BY SALESREP.S_NAME
  /*13*/CREATE VIEW TOTAL_SALE AS
  SELECT SALESREP.S_NAME, INVOICE.INV_NUM, INVOICE.INV_TOTAL, 
  (INVOICE.INV_TOTAL*SALESREP.S_COMM) AS "Total Commission",
  ((INVOICE.INV_TOTAL*SALESREP.S_COMM)+INVOICE.INV_TOTAL) AS "Total Sale"
  FROM SALESREP, INVOICE
  WHERE INVOICE.S_ID = SALESREP.S_ID
  ORDER BY SALESREP.S_NAME
  /*14*/CREATE VIEW TOTAL_SALE AS 
SELECT SALESREP.S_NAME, INVOICE.INV_NUM, INVOICE.CAR_NUM, INVOICE.INV_TOTAL, 
  (INVOICE.INV_TOTAL*SALESREP.S_COMM) AS "Total Commission",
  ((INVOICE.INV_TOTAL*SALESREP.S_COMM)+INVOICE.INV_TOTAL) AS "Total Sale"
  FROM SALESREP, INVOICE
  WHERE INVOICE.S_ID = SALESREP.S_ID
  ORDER BY SALESREP.S_NAME;
  
SELECT TOTAL_SALE.*, CAR.CAR_NAME, CAR.CAR_MODEL, CAR.CAR_YEAR, CAR.CAR_PRICE
  FROM TOTAL_SALE, CAR
  WHERE TOTAL_SALE.CAR_NUM=CAR.CAR_NUM ;
